### ISSUE TITLE
Lower Python version requirement

### ISSUE THREAD

**Issue by riffnshred** [coreyjs/nhl-api-py#22]
I got someone working on a fix for the nhl-led-scoreboard project and he's using your library to do so. The only issue I got is that some of my requirements breaks using Python 3.10 and up. would it be possible to make Python 3.9 the minimum requirement on your repo?

cheers

**Comment by coreyjs** [comment]
Yea, that shouldn't be a problem.  I can look into that soon.

**Comment by riffnshred** [comment]
Thanks !!!
