### ISSUE TITLE
Updating score_now() to take an Optional date

### ISSUE THREAD

**Issue by azaroth08** [coreyjs/nhl-api-py#34]
when you go to the endpoint "https://api-web.nhle.com/v1/score/now" it auto puts the date in.  The problem being that now will default to the previous day's date until noon.  Could I submit a PR that optionally lets that function also take a date to get that day's score before noon.

**Comment by coreyjs** [comment]
These "/now" endpoints kinda suck.  They are redirects within the nhl system.  So having an optional date would be great.

**Comment by coreyjs** [comment]
It would be "https://api-web.nhle.com/v1/score/2024-02-13", if im not mistaken?  Takes in a date.

**Comment by azaroth08** [comment]
Yeah.  i've been running the change locally and it passed the tests. Not a single issue.  As much as the now is convenient the nhl dictating that now changes over at such an arbitrary time (noon EST) is more if a pain than its worth
"INFO:root:API URL: https://api-web.nhle.com/v1/score/2024-02-13" It's also important to add the leading zeroes for months <10 and days <10.

**Comment by coreyjs** [comment]
Yea I agree.  Im all for making this easier on end user.

**Comment by coreyjs** [comment]
v2.2.7 has this now.
