### ISSUE TITLE
Add enpoint for goalies in stats

### ISSUE THREAD

**Issue by Paparadis** [coreyjs/nhl-api-py#53]
When checking API calls on the [goalies stats page](https://www.nhl.com/stats/goalies), another endpoint seems to exist only for goalers. 
![image](https://github.com/coreyjs/nhl-api-py/assets/54871797/971f295c-afa0-433d-86b9-e99e51137975)
"https://api.nhle.com/stats/rest/en/goalie/summary"

The endpoint seems to work similarly to that of skaters.

Would be great to add that to the stats functions available, and maybe create one function to merge skaters and goalers stats quickly.

**Comment by coreyjs** [comment]
Ah goalies, I forgot about them.  Yea Ill get that added.
