### ISSUE TITLE
client.schedule.get_schedule(date=today) returns more than I would have expected.

### ISSUE THREAD

**Issue by Btibert3** [coreyjs/nhl-api-py#70]
**Describe the bug**

I wanted to get today's games. Basically just the game id and info (teams, location, etc.) and am getting much more data than I expected relative to the call intent.  

It could be me, but wanted to log this here just in case, but its possible I don't quite grok what this call should yield.

**To Reproduce**

```
import datetime 
from nhlpy import NHLClient

# setup
today = datetime.date.today()
today = today.strftime("%Y-%m-%d")

# init the client
client = NHLClient()
# get today's date
sched = client.schedule.get_schedule(date=today)
sched.get('numberOfGames')
```
I get 45.  I see multiple game dates.  

**Expected behavior**
I would see entries related to the single day and ultimately three games.  

**Screenshots**

![image](https://github.com/user-attachments/assets/8f052109-cf13-4f85-9fde-3e5169bbfe1a)

**Desktop (please complete the following information):**
 - Google Colab
 - https://colab.research.google.com/drive/1u9KB7DBLVSh1PHleDmLpIHUmesxz11ut?usp=sharing

**Additional context**
I didn't look at the code (yet) but wanted to log because its entirely possible that the NHL API is off, but I would expect that if we isolate down to a single day, only that day is returned.

**Comment by coreyjs** [comment]
So this is what's annoying about the new NHL apis.  `get_schedule` will return the entire week of games, if given a `date` it will return all the games for the week starting with `date` (from what I can tell is the [0] element in `gameWeek`).  I agree it's confusing, I think I can update this to only return games for `date`, and just filter down what the NHL send me.


---
Example `https://api-web.nhle.com/v1/schedule/2024-10-08` , despite being for `10/8` its returning the entire week.

---

Best approach I think is I'll update `get_schedule(date)` to return only games for the given date, and maybe add another method `get_weekly_schedule(...)` or something similar.

**Comment by Btibert3** [comment]
Got it, makes sense to me.  And you are a wizard for already having some changes implemented!  Hat tip.

**Comment by coreyjs** [comment]
There's gonna be a few of these that are weird.  I wanted to get everything in code, and then I figured as I used it more I would refine it a bit.  Thanks for catching this. @Btibert3
