### ISSUE TITLE
Get Schedule - Odds Partners

### ISSUE THREAD

**Issue by Btibert3** [coreyjs/nhl-api-py#75]
**Describe the bug**
Using the call from the README docs throws a Key Error for oddsPartners

**To Reproduce**
1. `pip install nhl-api-py`
2. `from nhlpy import NHLClient`
3. `client = NHLClient()`
4. `games_test = client.schedule.get_schedule(date="2021-01-13")` throws the error

**Expected behavior**
The call to complete successfully

**Screenshots**

![image](https://github.com/user-attachments/assets/5ee866f9-fc9a-4d54-b1a7-0580250e6e8c)

**Desktop (please complete the following information):**
 - OS: Google Colab

**Additional context**

**Comment by coreyjs** [comment]
Ah, edge case, no odds going back that far.  I'll have a fix in shortly.

**Comment by coreyjs** [comment]
Thanks for reporting this, I really do appreciate it.  Fix is in version 2.12.1

**Comment by Btibert3** [comment]
Amazing, thank you for such a fast turnaround.  I haven't had much time to dive into the codebase, so I apologize for just lobbing tickets over the wall.  This resulted from me mapping out an idea for a course I am running next semester, which would revolve around the need to get all game ids for a season, and then grab/parse the PBP data. 

Thank you for your hard work on this library, I know it's a tall task to pull all of this together.
