### ISSUE TITLE
skater_stats_with_query_context - Returning 70 players

### ISSUE THREAD

**Issue by Btibert3** [coreyjs/nhl-api-py#83]
**Describe the bug**
I don't know if it's a bug, but I attempted to grab skater stats for all forwards this season via the code below.  The code returned 70 players across 24 stats.  Is there a chance I a missing a way to paginate?

**To Reproduce**
I outlined a Colab notebook here: https://colab.research.google.com/drive/1T5m8VZWo5Af6w-0kqVvBk78LmC9GTTny?usp=sharing

```
# remove filters, just forwards for this season is the idea
filters = [
    SeasonQuery(season_start="20242025", season_end="20242025"),
    PositionQuery(position=PositionTypes.ALL_FORWARDS)
]

query_builder = QueryBuilder()
query_context: QueryContext = query_builder.build(filters=filters)

data = client.stats.skater_stats_with_query_context(
    report_type='summary',
    query_context=query_context,
    aggregate=True
)
```

The above code sample yields 70 players.

**Expected behavior**
All of the forwards this year (at least more than 70).

**Screenshots**
![image](https://github.com/user-attachments/assets/a064c975-8a93-43dd-84da-08a6427ef086)

**Desktop (please complete the following information):**
Google Colab.

**Comment by masorz** [comment]
There are `start` and` limit` parameters. By default, the method returns `70 `entries. The maximum number of players I retrieved with a single API call is `100.`
Solution:
`start = 0
limit = 100
skaters_stats = {"data": []}
iteration = 0

while True:
    response = client.stats.skater_stats_with_query_context(
        report_type="summary",
        query_context=query_context,
        aggregate=False,
        start=start,
        limit=limit,
    )
    if not response["data"]:
        break
    skaters_stats["data"].extend(response["data"])
    start += limit
    iteration += 1
    print(f"Iteration: {iteration}")

skaters_stats["total"] = len(skaters_stats["data"])`

**Comment by coreyjs** [comment]
Thanks @masorz !  Yea the methods themselves I just defaulted to 70, so you could set that to 100 and just track and loop like the snippet above.

**Comment by Btibert3** [comment]
Awesome, I didn't pick up on that.  Thank you!

**Comment by coreyjs** [comment]
I think Ill add this to the readme in examples, or actually get a working notebook with examples.

**Comment by Btibert3** [comment]
I don't know if this is something you would be interested in, but I use Github Pages to host static sites for my courses.  I am the farthest thing from a frontend dev, but really enjoy using Quarto to build the sites.  It's simple to get started and allows you to mix text with code examples in one go.  An example from one of my courses this semester: https://btibert3.github.io/BA882-Fall24/

**Comment by coreyjs** [comment]
@Btibert3 That's very interesting, im gonna look into that.  I stay far away from the front end and just chatgpt myself something that works, but this looks pretty solid.
