### ISSUE TITLE
404 error for Edmonton 1990-1991

### ISSUE THREAD

**Issue by B-D-T** [coreyjs/nhl-api-py#84]
## Describe the bug  

The `get_season_schedule` method returns an error for Edmonton in the 1990-1991 season.

> `json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I believe this is because the NHL's API returns a 404 for that request. In which case, that may be out of scope for fixes to this package.

## To Reproduce  

```python
client = NHLClient(verbose=True)
schedule = Schedule(client._http_client)
schedule.get_season_schedule("EDM", "19901991") # returns error above
```

## Expected behavior  

Returns JSON formatted data with Edmonton's games from the 1990-1991 season.

## Further details  

This is the code for `get_season_schedule`:  

```python
   def get_season_schedule(self, team_abbr: str, season: str) -> dict:
        return self.client.get(resource=f"club-schedule-season/{team_abbr}/{season}").json()
```

If we run just the `.get`: 

`self.client.get(resource=f"club-schedule-season/{team_abbr}/{season}")`

it returns

> `<Response [404 Not Found]`

**Comment by coreyjs** [comment]
Ill check this out, thanks for opening the ticket!

**Comment by coreyjs** [comment]
That's interesting, https://api-web.nhle.com/v1/club-schedule-season/EDM/19901991 returns a 404, but 19891990 and 19911992 work.  It seems to be something with their data, but I agree this should not "error", I'll find a good solution for this.  

Its also broke on their own site https://www.nhl.com/oilers/schedule/1990/fullseason

**Comment by B-D-T** [comment]
Thanks. I sent a note to NHL.com to alert them to root issue.

I'll piece together the data from the opponents' schedules. I was just surprised when I had `gameId` values with only 1 record.
