### ISSUE TITLE
Get League Schedule for the entire Season

### ISSUE THREAD

**Issue by Btibert3** [coreyjs/nhl-api-py#92]
**Is your feature request related to a problem? Please describe.**
It appears that there are various ways to slice out schedules; for a given day, for a team, a week, but not the entire season across the league.  At first blush I expected this using the `.get_season_schedule` method but that requires a team id.  

**Describe the solution you'd like**
An approach similar to `.get_season_schedule` but for the entire league.  My use case would be to grab the gameids for a season in order to grab the results and PBP datasets for historical analysis and modeling.  As such, my need isn't the full object, but simply a list of gameids, but admittedly that might be too narrow.  My framing is an endpoint that I previously used from here: http://www.nicetimeonice.com/api, which would yield an array of gameids.

**Describe alternatives you've considered**
I could walk or daily schedules.

**Additional context**

**Comment by coreyjs** [comment]
This is one of those endpoints where there just isn't a clean implementation from the NHL.  They build all these separate endpoints to facilitate their web site and from an API standpoint they are confusing and kinda suck.  I think there are two solutions here.  

1. I use to have a section called `helpers` where I would put methods like this in there.  Ones that did lots of aggregation or called another endpoint many times.  Might be beneficial to have something like `client.helpers.get_gameids_by_season(year)` or such.

2. The only way to do this now is to get all team abbreviations from `client.teams.team_info()` and loop `get_season_schedule(team)`.  This is essentially what I would do in option 1.

**Comment by coreyjs** [comment]
released in ver 2.17.0

**Comment by Btibert3** [comment]
🚀
